### ISSUE TITLE
1.14.3 Crash on sort in chest

### ISSUE THREAD

**Issue by ADHDDamien** [kyrptonaught/Inventory-Sorter#1]
Using Fabric 1.14.3 server if you sort a chest it breaks, if it helps the contents of the chest are as such: https://i.imgur.com/s1u99Qo.png

I have no other mods that should conflict (pretty much just optifine and optifabric and REI) and definitely none that change anything chest/inventory wise other than REI I suppose.

Reproduction steps: Pretty much open a chest and the second you click the sort button it crashes and says "The server is closed" and then crashes the server.

If you need any more info let me know and I can try to get it for you! But here is the crash report below.

```
java.lang.NoSuchMethodError: net.minecraft.class_1792.method_7848()Lnet/minecraft/class_2561;
	at net.kyrptonaught.inventorysorter.SortableStack.getCleanName(SortableStack.java:17)
	at net.kyrptonaught.inventorysorter.SortableStack.compareTo(SortableStack.java:28)
	at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:188)
	at java.util.Arrays.sort(Arrays.java:1312)
	at java.util.Arrays.sort(Arrays.java:1506)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at java.util.Collections.sort(Collections.java:141)
	at net.kyrptonaught.inventorysorter.InventorySorter.sortInv(InventorySorter.java:43)
	at net.kyrptonaught.inventorysorter.InventorySorter.lambda$null$0(InventorySorter.java:29)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:135)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:114)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:695)
	at net.minecraft.class_1255.method_5383(class_1255.java:99)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:679)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4893543144 bytes (4666 MB) / 6284115968 bytes (5993 MB) up to 6284115968 bytes (5993 MB)
```

**Comment by kyrptonaught** [comment]
Thanks for the detailed write-up, this should be taken care of in version 1.2.1

**Comment by ADHDDamien** [comment]
Hey thanks for the super fast fix and no problem! Unfortunately it seems to still be a bit of a problem (Everything else is still the same as above and same reproduction but slightly new error with slightly different numbers and the contents of the chest were slightly different with just like a few pieces of dirt and a recipe table and some torches, can provide screenshot if necessary but everythings closed currently due to server crash lol):

`java.lang.NoSuchMethodError: net.minecraft.class_1792.method_7848()Lnet/minecraft/class_2561;
	at net.kyrptonaught.inventorysorter.SortableStack.getCleanName(SortableStack.java:17)
	at net.kyrptonaught.inventorysorter.SortableStack.compareTo(SortableStack.java:28)
	at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:188)
	at java.util.Arrays.sort(Arrays.java:1312)
	at java.util.Arrays.sort(Arrays.java:1506)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at java.util.Collections.sort(Collections.java:141)
	at net.kyrptonaught.inventorysorter.InventorySorter.sortInv(InventorySorter.java:46)
	at net.kyrptonaught.inventorysorter.InventorySorter.lambda$null$0(InventorySorter.java:32)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:135)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:114)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:695)
	at net.minecraft.class_1255.method_18857(class_1255.java:123)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:680)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635)
	at java.lang.Thread.run(Thread.java:748)`

Hope that helps, if you need anything let me know!

**Comment by kyrptonaught** [comment]
Hmm could you give this version a try? 
[InventorySorter-1.2.2.zip](https://github.com/kyrptonaught/Inventory-Sorter/files/3352249/InventorySorter-1.2.2.zip)

If it still doesn't work can you verify you are running the latest version of fabric/fabric loader?

**Comment by ADHDDamien** [comment]
You nailed it with that one, it worked perfectly! Thank you!

**Comment by kyrptonaught** [comment]
No problem! You made it super easy with the crash logs! Thanks for trying out the mod, don't be afraid to send me any suggestion or any other errors you may come across!
