### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by Luro02** [kyrptonaught/Inventory-Sorter#26]
Taken from the server console (not sure if this is useful):
```
[08:57:50] [Server thread/FATAL]: Error executing task on Server
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_212]
at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_212]
at net.minecraft.class_1703.getInventory(class_1703.java:748) ~[intermediary-server.jar:?]
at net.kyrptonaught.inventorysorter.InventorySortPacket.lambda$registerReceivePacket$0(InventorySortPacket.java:26) ~[InventorySorter-1.7.0-1.16.jar:?]
at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154) ~[intermediary-server.jar:?]
at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739) ~[intermediary-server.jar:?]
at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:724) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) ~[intermediary-server.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by kyrptonaught** [comment]
What caused this to occur?

**Comment by Luro02** [comment]
I don't know. I found this while scrolling through the server logs and thought it would be useful to report this issue.

**Comment by Luro02** [comment]
Okay I think I found out what causes this issue. In the modpack that I am playing there is a mod called `slotlink` used, which makes it possible to link multiple chests.

Through the `Storage Request` block one can remove items from the storage network.
![Screenshot_20200806_141605](https://user-images.githubusercontent.com/24826124/89530809-68956c00-d7ef-11ea-8c96-ee32a2bde8eb.png)

When you try to sort the interface by pressing shift + middle mouse button, the above exception is logged on the server.

**Comment by kyrptonaught** [comment]
This should now be fixed
