### ISSUE TITLE
Sorting Multiple Items Isn't Functioning On Servers After 1.5.0 Update

### ISSUE THREAD

**Issue by Astraliccc** [kyrptonaught/Inventory-Sorter#6]
Inventory Sorter: 1.5.0
Fabric Api: 0.3.1
Fabric Game/mappings: 1.14.4+build 9
Loader Version: 0.4.8+build.159
Java: Oracle java 8 u221

When using the sort button on a server nothing happens and this prints out to the console log. I tried getting brand new fabric files as well and I am still getting the same issue so it seems to be a problem with the mod at least on the most recent version.

This only occurs if there is more than 1 item being sorted, 1 item sorts without any errors and happens in all interfaces. 

No issues in Single player using the same versions and mods and such.

`[11:33:47] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
        at net.kyrptonaught.inventorysorter.SortableStack.getSortString(SortableStack.java:24) ~[InventorySorter-1.5.0.jar:?]
        at net.kyrptonaught.inventorysorter.SortableStack.compareTo(SortableStack.java:40) ~[InventorySorter-1.5.0.jar:?]
        at java.util.ComparableTimSort.countRunAndMakeAscending(Unknown Source) ~[?:1.8.0_221]
        at java.util.ComparableTimSort.sort(Unknown Source) ~[?:1.8.0_221]
        at java.util.Arrays.sort(Unknown Source) ~[?:1.8.0_221]
        at java.util.Arrays.sort(Unknown Source) ~[?:1.8.0_221]
        at java.util.ArrayList.sort(Unknown Source) ~[?:1.8.0_221]
        at java.util.Collections.sort(Unknown Source) ~[?:1.8.0_221]
        at net.kyrptonaught.inventorysorter.InventoryHelper.sortInv(InventoryHelper.java:26) ~[InventorySorter-1.5.0.jar:?]
        at net.kyrptonaught.inventorysorter.InventorySortPacket.lambda$null$0(InventorySortPacket.java:25) ~[InventorySorter-1.5.0.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:712) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:706) [intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:691) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:646) [intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]`

**Comment by kyrptonaught** [comment]
Thank you for the detailed report, should be fixed in 1.5.1.
