### ISSUE TITLE
Error on starting the server

### ISSUE THREAD

**Issue by VitalityDoS** [kyrptonaught/Inventory-Sorter#60]
Hi, I have this error when I try to sttart my server. Aparently, the mods do not detect fabric, but I have other mods (carpet) instaled without problems.

[20:05:53] [main/WARN]: Mod resolution failed
[20:05:53] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE inventorysorter 1.8.0-1.18 {depends fabric @ [*]}, ROOT_FORCELOAD_SINGLE inventorysorter 1.8.0-1.18]
[20:05:53] [main/INFO]: Reason: [HARD_DEP inventorysorter 1.8.0-1.18 {depends fabric @ [*]}]
[20:05:53] [main/INFO]: Fix: add [add:fabric 1 ([(-∞,∞)])], remove [], replace []
[20:05:53] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Install fabric, any version.
Unmet dependency listing:
         - Mod 'Inventory Sorter' (inventorysorter) 1.8.0-1.18 requires any version of fabric, which is missing!
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:188) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) [fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.8.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.8.jar:?]
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Install fabric, any version.
Unmet dependency listing:
         - Mod 'Inventory Sorter' (inventorysorter) 1.8.0-1.18 requires any version of fabric, which is missing!
        at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:222) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:186) ~[fabric-loader-0.12.8.jar:?]
        ... 8 more

**Comment by kyrptonaught** [comment]
Look alike you're missing:

https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by VitalityDoS** [comment]
> Look alike you're missing:
> 
> https://www.curseforge.com/minecraft/mc-mods/fabric-api

Iep, it worked. I forgot adding it on the server side. Thanks a lot! It works perfect.
